package pe.gob.inabif.model;

// Generated 02/03/2016 11:58:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tsocurrencia generated by hbm2java
 */
public class TsocurrenciaResponse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idocurrencia;
	private int idestado;
	private int idsubcategoria;
	private String ocufechaocurrencia;
	private String ocuresidente;
	private String ocunumeroexpediente;
	private String ocudetalle;
	private int ocuestado;
	private Long usuregistra;
	private String fecharegistra;
	private Long usuactualiza;
	private String fechaactualiza;
	private Long usuelimina;
	private String fechaelimina;

	public long getIdocurrencia() {
		return idocurrencia;
	}

	public void setIdocurrencia(long idocurrencia) {
		this.idocurrencia = idocurrencia;
	}

	public int getIdestado() {
		return idestado;
	}

	public void setIdestado(int idestado) {
		this.idestado = idestado;
	}

	public int getIdsubcategoria() {
		return idsubcategoria;
	}

	public void setIdsubcategoria(int idsubcategoria) {
		this.idsubcategoria = idsubcategoria;
	}

	public String getOcufechaocurrencia() {
		return ocufechaocurrencia;
	}

	public void setOcufechaocurrencia(String ocufechaocurrencia) {
		this.ocufechaocurrencia = ocufechaocurrencia;
	}

	public String getOcuresidente() {
		return ocuresidente;
	}

	public void setOcuresidente(String ocuresidente) {
		this.ocuresidente = ocuresidente;
	}

	public String getOcunumeroexpediente() {
		return ocunumeroexpediente;
	}

	public void setOcunumeroexpediente(String ocunumeroexpediente) {
		this.ocunumeroexpediente = ocunumeroexpediente;
	}

	public String getOcudetalle() {
		return ocudetalle;
	}

	public void setOcudetalle(String ocudetalle) {
		this.ocudetalle = ocudetalle;
	}

	public int getOcuestado() {
		return ocuestado;
	}

	public void setOcuestado(int ocuestado) {
		this.ocuestado = ocuestado;
	}

	public Long getUsuregistra() {
		return usuregistra;
	}

	public void setUsuregistra(Long usuregistra) {
		this.usuregistra = usuregistra;
	}

	public String getFecharegistra() {
		return fecharegistra;
	}

	public void setFecharegistra(String fecharegistra) {
		this.fecharegistra = fecharegistra;
	}

	public Long getUsuactualiza() {
		return usuactualiza;
	}

	public void setUsuactualiza(Long usuactualiza) {
		this.usuactualiza = usuactualiza;
	}

	public String getFechaactualiza() {
		return fechaactualiza;
	}

	public void setFechaactualiza(String fechaactualiza) {
		this.fechaactualiza = fechaactualiza;
	}

	public Long getUsuelimina() {
		return usuelimina;
	}

	public void setUsuelimina(Long usuelimina) {
		this.usuelimina = usuelimina;
	}

	public String getFechaelimina() {
		return fechaelimina;
	}

	public void setFechaelimina(String fechaelimina) {
		this.fechaelimina = fechaelimina;
	}

}
