package pe.gob.inabif.model;
// Generated 02/03/2016 11:58:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tsocurraccion generated by hbm2java
 */
public class Tsocurraccion  implements java.io.Serializable {


     private long idocurraccion;
     private int idocurrencia;
     private String oacdetalle;
     private Long usuregistra;
     private Date fecharegistra;
     private Long usuactualiza;
     private Date fechaactualiza;
     private Long usuelimina;
     private Date fechaelimina;
     
    public Tsocurraccion() {
    }

	
    public Tsocurraccion(long idocurraccion) {
        this.idocurraccion = idocurraccion;
    }
    public Tsocurraccion(long idocurraccion, int idocurrencia, String oacdetalle, Long usuregistra, Date fecharegistra, Long usuactualiza, Date fechaactualiza, Long usuelimina, Date fechaelimina) {
       this.idocurraccion = idocurraccion;
       this.idocurrencia = idocurrencia;
       this.oacdetalle = oacdetalle;
       this.usuregistra = usuregistra;
       this.fecharegistra = fecharegistra;
       this.usuactualiza = usuactualiza;
       this.fechaactualiza = fechaactualiza;
       this.usuelimina = usuelimina;
       this.fechaelimina = fechaelimina;
    }
   
    public long getIdocurraccion() {
        return this.idocurraccion;
    }
    
    public void setIdocurraccion(long idocurraccion) {
        this.idocurraccion = idocurraccion;
    }
    public int getIdocurrencia() {
        return this.idocurrencia;
    }
    
    public void setIdocurrencia(int idocurrencia) {
        this.idocurrencia = idocurrencia;
    }
    public String getOacdetalle() {
        return this.oacdetalle;
    }
    
    public void setOacdetalle(String oacdetalle) {
        this.oacdetalle = oacdetalle;
    }
    public Long getUsuregistra() {
        return this.usuregistra;
    }
    
    public void setUsuregistra(Long usuregistra) {
        this.usuregistra = usuregistra;
    }
    public Date getFecharegistra() {
        return this.fecharegistra;
    }
    
    public void setFecharegistra(Date fecharegistra) {
        this.fecharegistra = fecharegistra;
    }
    public Long getUsuactualiza() {
        return this.usuactualiza;
    }
    
    public void setUsuactualiza(Long usuactualiza) {
        this.usuactualiza = usuactualiza;
    }
    public Date getFechaactualiza() {
        return this.fechaactualiza;
    }
    
    public void setFechaactualiza(Date fechaactualiza) {
        this.fechaactualiza = fechaactualiza;
    }
    public Long getUsuelimina() {
        return this.usuelimina;
    }
    
    public void setUsuelimina(Long usuelimina) {
        this.usuelimina = usuelimina;
    }
    public Date getFechaelimina() {
        return this.fechaelimina;
    }
    
    public void setFechaelimina(Date fechaelimina) {
        this.fechaelimina = fechaelimina;
    }
}


