package Modelo;
// Generated 02/03/2016 11:58:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tscategoria generated by hbm2java
 */
@XmlRootElement
public class Tscategoria  implements java.io.Serializable {

     private long idcategoria;
     private int idtipo;
     private String ctgdescripcion;
     private int estado;
     private Long usuregistra;
     private Date fecharegistra;
     private Long usuactualiza;
     private Date fechaactualiza;
     private Long usuelimina;
     private Date fechaelimina;

    public Tscategoria() {
    }

	
    public Tscategoria(long idcategoria) {
        this.idcategoria = idcategoria;
    }
    
    public Tscategoria(long idcategoria, int idtipo, String ctgdescripcion, int estado, Long usuregistra, Date fecharegistra, Long usuactualiza, Date fechaactualiza, Long usuelimina, Date fechaelimina) {
       this.idcategoria = idcategoria;
       this.idtipo = idtipo;
       this.ctgdescripcion = ctgdescripcion;
       this.estado = estado;
       this.usuregistra = usuregistra;
       this.fecharegistra = fecharegistra;
       this.usuactualiza = usuactualiza;
       this.fechaactualiza = fechaactualiza;
       this.usuelimina = usuelimina;
       this.fechaelimina = fechaelimina;
    }
   
    public long getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(long idcategoria) {
        this.idcategoria = idcategoria;
    }
    public int getIdtipo() {
        return this.idtipo;
    }
    
    public void setIdtipo(int idtipo) {
        this.idtipo = idtipo;
    }
    public String getCtgdescripcion() {
        return this.ctgdescripcion;
    }
    
    public void setCtgdescripcion(String ctgdescripcion) {
        this.ctgdescripcion = ctgdescripcion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Long getUsuregistra() {
        return this.usuregistra;
    }
    
    public void setUsuregistra(Long usuregistra) {
        this.usuregistra = usuregistra;
    }
    public Date getFecharegistra() {
        return this.fecharegistra;
    }
    
    public void setFecharegistra(Date fecharegistra) {
        this.fecharegistra = fecharegistra;
    }
    public Long getUsuactualiza() {
        return this.usuactualiza;
    }
    
    public void setUsuactualiza(Long usuactualiza) {
        this.usuactualiza = usuactualiza;
    }
    public Date getFechaactualiza() {
        return this.fechaactualiza;
    }
    
    public void setFechaactualiza(Date fechaactualiza) {
        this.fechaactualiza = fechaactualiza;
    }
    public Long getUsuelimina() {
        return this.usuelimina;
    }
    
    public void setUsuelimina(Long usuelimina) {
        this.usuelimina = usuelimina;
    }
    public Date getFechaelimina() {
        return this.fechaelimina;
    }
    
    public void setFechaelimina(Date fechaelimina) {
        this.fechaelimina = fechaelimina;
    }
}


