package Modelo;
// Generated 02/03/2016 11:58:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tsestado generated by hbm2java
 */
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tsestado generated by hbm2java
 */
@XmlRootElement
public class Tsestado  implements java.io.Serializable {


     private int idestado;
     private String tsdetalle;     

    public Tsestado() {
    }

	
    public Tsestado(int idestado) {
        this.idestado = idestado;
    }
    public Tsestado(int idestado, String tsdetalle) {
       this.idestado = idestado;
       this.tsdetalle = tsdetalle;       
    }
   
    public int getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(int idestado) {
        this.idestado = idestado;
    }
    public String getTsdetalle() {
        return this.tsdetalle;
    }
    
    public void setTsdetalle(String tsdetalle) {
        this.tsdetalle = tsdetalle;
    }
}


