package Modelo;
// Generated 02/03/2016 11:58:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tsocurrencia generated by hbm2java
 */
public class Tsocurrencia  implements java.io.Serializable {


     private long idocurrencia;
     private int idestado;
     private int idsubcategoria;
     private Date ocufechaocurrencia;
     private String ocuresidente;
     private String ocunumeroexpediente;
     private String ocudetalle;
     private int ocuestado;
     private Long usuregistra;
     private Date fecharegistra;
     private Long usuactualiza;
     private Date fechaactualiza;
     private Long usuelimina;
     private Date fechaelimina;

    public Tsocurrencia() {
    }

	
    public Tsocurrencia(long idocurrencia) {
        this.idocurrencia = idocurrencia;
    }
    public Tsocurrencia(long idocurrencia, int idestado, int idsubcategoria, Date ocufechaocurrencia, String ocuresidente, String ocunumeroexpediente, String ocudetalle, int ocuestado, Long usuregistra, Date fecharegistra, Long usuactualiza, Date fechaactualiza, Long usuelimina, Date fechaelimina) {
       this.idocurrencia = idocurrencia;
       this.idestado = idestado;
       this.idsubcategoria = idsubcategoria;
       this.ocufechaocurrencia = ocufechaocurrencia;
       this.ocuresidente = ocuresidente;
       this.ocunumeroexpediente = ocunumeroexpediente;
       this.ocudetalle = ocudetalle;
       this.ocuestado = ocuestado;
       this.usuregistra = usuregistra;
       this.fecharegistra = fecharegistra;
       this.usuactualiza = usuactualiza;
       this.fechaactualiza = fechaactualiza;
       this.usuelimina = usuelimina;
       this.fechaelimina = fechaelimina;
    }
   
    public long getIdocurrencia() {
        return this.idocurrencia;
    }
    
    public void setIdocurrencia(long idocurrencia) {
        this.idocurrencia = idocurrencia;
    }
    public int getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(int idestado) {
        this.idestado = idestado;
    }
    public int getIdsubcategoria() {
        return this.idsubcategoria;
    }
    
    public void setIdsubcategoria(int idsubcategoria) {
        this.idsubcategoria = idsubcategoria;
    }
    public Date getOcufechaocurrencia() {
        return this.ocufechaocurrencia;
    }
    
    public void setOcufechaocurrencia(Date ocufechaocurrencia) {
        this.ocufechaocurrencia = ocufechaocurrencia;
    }
    public String getOcuresidente() {
        return this.ocuresidente;
    }
    
    public void setOcuresidente(String ocuresidente) {
        this.ocuresidente = ocuresidente;
    }
    public String getOcunumeroexpediente() {
        return this.ocunumeroexpediente;
    }
    
    public void setOcunumeroexpediente(String ocunumeroexpediente) {
        this.ocunumeroexpediente = ocunumeroexpediente;
    }
    public String getOcudetalle() {
        return this.ocudetalle;
    }
    
    public void setOcudetalle(String ocudetalle) {
        this.ocudetalle = ocudetalle;
    }
    public int getOcuestado() {
        return this.ocuestado;
    }
    
    public void setOcuestado(int ocuestado) {
        this.ocuestado = ocuestado;
    }
    
    public Long getUsuregistra() {
        return this.usuregistra;
    }
    
    public void setUsuregistra(Long usuregistra) {
        this.usuregistra = usuregistra;
    }
    public Date getFecharegistra() {
        return this.fecharegistra;
    }
    
    public void setFecharegistra(Date fecharegistra) {
        this.fecharegistra = fecharegistra;
    }
    public Long getUsuactualiza() {
        return this.usuactualiza;
    }
    
    public void setUsuactualiza(Long usuactualiza) {
        this.usuactualiza = usuactualiza;
    }
    public Date getFechaactualiza() {
        return this.fechaactualiza;
    }
    
    public void setFechaactualiza(Date fechaactualiza) {
        this.fechaactualiza = fechaactualiza;
    }
    public Long getUsuelimina() {
        return this.usuelimina;
    }
    
    public void setUsuelimina(Long usuelimina) {
        this.usuelimina = usuelimina;
    }
    public Date getFechaelimina() {
        return this.fechaelimina;
    }
    
    public void setFechaelimina(Date fechaelimina) {
        this.fechaelimina = fechaelimina;
    }

}


