package Modelo;
// Generated 02/03/2016 11:58:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tssubcategori generated by hbm2java
 */
@XmlRootElement
public class Tssubcategori  implements java.io.Serializable {


     private long idsubcategoria;
     private int idcategoria;
     private String sctdescripcion;
     private Boolean estado;
     private Long usuregistra;
     private Date fecharegistra;
     private Long usuactualiza;
     private Date fechaactualiza;
     private Long usuelimina;
     private Date fechaelimina;

    public Tssubcategori() {
    }

	
    public Tssubcategori(long idsubcategoria) {
        this.idsubcategoria = idsubcategoria;
    }
    public Tssubcategori(long idsubcategoria, int idcategoria, String sctdescripcion, Boolean estado, Long usuregistra, Date fecharegistra, Long usuactualiza, Date fechaactualiza, Long usuelimina, Date fechaelimina) {
       this.idsubcategoria = idsubcategoria;
       this.idcategoria = idcategoria;
       this.sctdescripcion = sctdescripcion;
       this.estado = estado;
       this.usuregistra = usuregistra;
       this.fecharegistra = fecharegistra;
       this.usuactualiza = usuactualiza;
       this.fechaactualiza = fechaactualiza;
       this.usuelimina = usuelimina;
       this.fechaelimina = fechaelimina;
    }
   
    public long getIdsubcategoria() {
        return this.idsubcategoria;
    }
    
    public void setIdsubcategoria(long idsubcategoria) {
        this.idsubcategoria = idsubcategoria;
    }
    public int getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(int idcategoria) {
        this.idcategoria = idcategoria;
    }
    public String getSctdescripcion() {
        return this.sctdescripcion;
    }
    
    public void setSctdescripcion(String sctdescripcion) {
        this.sctdescripcion = sctdescripcion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Long getUsuregistra() {
        return this.usuregistra;
    }
    
    public void setUsuregistra(Long usuregistra) {
        this.usuregistra = usuregistra;
    }
    public Date getFecharegistra() {
        return this.fecharegistra;
    }
    
    public void setFecharegistra(Date fecharegistra) {
        this.fecharegistra = fecharegistra;
    }
    public Long getUsuactualiza() {
        return this.usuactualiza;
    }
    
    public void setUsuactualiza(Long usuactualiza) {
        this.usuactualiza = usuactualiza;
    }
    public Date getFechaactualiza() {
        return this.fechaactualiza;
    }
    
    public void setFechaactualiza(Date fechaactualiza) {
        this.fechaactualiza = fechaactualiza;
    }
    public Long getUsuelimina() {
        return this.usuelimina;
    }
    
    public void setUsuelimina(Long usuelimina) {
        this.usuelimina = usuelimina;
    }
    public Date getFechaelimina() {
        return this.fechaelimina;
    }
    
    public void setFechaelimina(Date fechaelimina) {
        this.fechaelimina = fechaelimina;
    }
    
}


