package Modelo;
// Generated 02/03/2016 11:58:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tstipo generated by hbm2java
 */
@XmlRootElement
public class Tstipo  implements java.io.Serializable {


     private long idtipo;
     private String tipdescricion;
     private Boolean estado;
     private Long usuregistra;
     private Date fecharegistra;
     private Long usuactualiza;
     private Date fechaactualiza;
     private Long usuelimina;
     private Date fechaelimina;
     private Set tscategorias = new HashSet(0);

    public Tstipo() {
    }

	
    public Tstipo(long idtipo) {
        this.idtipo = idtipo;
    }
    public Tstipo(long idtipo, String tipdescricion, Boolean estado, Long usuregistra, Date fecharegistra, Long usuactualiza, Date fechaactualiza, Long usuelimina, Date fechaelimina, Set tscategorias) {
       this.idtipo = idtipo;
       this.tipdescricion = tipdescricion;
       this.estado = estado;
       this.usuregistra = usuregistra;
       this.fecharegistra = fecharegistra;
       this.usuactualiza = usuactualiza;
       this.fechaactualiza = fechaactualiza;
       this.usuelimina = usuelimina;
       this.fechaelimina = fechaelimina;
       this.tscategorias = tscategorias;
    }
   
    public long getIdtipo() {
        return this.idtipo;
    }
    
    public void setIdtipo(long idtipo) {
        this.idtipo = idtipo;
    }
    public String getTipdescricion() {
        return this.tipdescricion;
    }
    
    public void setTipdescricion(String tipdescricion) {
        this.tipdescricion = tipdescricion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Long getUsuregistra() {
        return this.usuregistra;
    }
    
    public void setUsuregistra(Long usuregistra) {
        this.usuregistra = usuregistra;
    }
    public Date getFecharegistra() {
        return this.fecharegistra;
    }
    
    public void setFecharegistra(Date fecharegistra) {
        this.fecharegistra = fecharegistra;
    }
    public Long getUsuactualiza() {
        return this.usuactualiza;
    }
    
    public void setUsuactualiza(Long usuactualiza) {
        this.usuactualiza = usuactualiza;
    }
    public Date getFechaactualiza() {
        return this.fechaactualiza;
    }
    
    public void setFechaactualiza(Date fechaactualiza) {
        this.fechaactualiza = fechaactualiza;
    }
    public Long getUsuelimina() {
        return this.usuelimina;
    }
    
    public void setUsuelimina(Long usuelimina) {
        this.usuelimina = usuelimina;
    }
    public Date getFechaelimina() {
        return this.fechaelimina;
    }
    
    public void setFechaelimina(Date fechaelimina) {
        this.fechaelimina = fechaelimina;
    }
    public Set getTscategorias() {
        return this.tscategorias;
    }
    
    public void setTscategorias(Set tscategorias) {
        this.tscategorias = tscategorias;
    }




}


